### ISSUE TITLE
Incorrect password leads to characteristic error

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-config#105]
When an incorrect password is entered, the user is prompted with a [398168aa-0111-4ec0-b1fa-171671270608](https://github.com/NebraLtd/hm-config/blob/master/gatewayconfig/constants.py#L72) characteristic error. 

Inconsistent behavior has been observed when an invalid password is entered. An invalid password is a password that is wrong by definition (eg too few characters). An incorrect password meets password requirements is wrong.

**Comment by posterzh** [comment]
Too few characters:
![image](https://user-images.githubusercontent.com/91350131/141255881-b9db0752-cdd3-4d0e-bafe-f81fc329dfa5.png)
![image](https://user-images.githubusercontent.com/91350131/141255922-db89c361-269f-4e5f-8094-2c3654f9a3ad.png)

Incorrect Password:
![image](https://user-images.githubusercontent.com/91350131/141256011-243f4ca7-652b-4459-92cf-9670d8f81284.png)
![image](https://user-images.githubusercontent.com/91350131/141256029-3c29d272-2103-4a5e-9b68-56158f29c2e8.png)

**Comment by posterzh** [comment]
After fixing the https://github.com/NebraLtd/hm-config/issues/105, the characteristic errors of https://github.com/NebraLtd/hm-config/issues/47 and https://github.com/NebraLtd/hm-config/issues/68 are also fixed.

**Comment by marvinmarnold** [comment]
> After fixing the #105, the characteristic errors of #47 and #68 are also fixed.

@posterzh I believe you need to make this note in the description of the PR or a commit message in order for those issues to automatically close: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
