### ISSUE TITLE
Meta analysis of bluetooth issues

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-config#115]
Related to #105, #47, #42, #46, #68

**Comment by posterzh** [comment]
After fixing the https://github.com/NebraLtd/hm-config/issues/105, the characteristic errors of https://github.com/NebraLtd/hm-config/issues/47 and https://github.com/NebraLtd/hm-config/issues/68 are also fixed.

**Comment by shawaj** [comment]
@posterzh we should get @NebraLtd/tech-support to test and verify and then close the issues if they are solved

**Comment by KevinWassermann94** [comment]
@posterzh @shawaj Absolutetly!

**Comment by shawaj** [comment]
P.S. great work. Glad to have some of these annoying niggly issues resolved
