### ISSUE TITLE
forget wifi: nmcli does not correctly forget wifi networks and prioritises based on signal strength

### ISSUE THREAD

**Issue by millerz1897** [NebraLtd/hm-config#131]
After upgrade two things happened

1) wifi reverted to previous configuration. (Which is difficult/near impossible) to change over Bluetooth)
2) hot spot no longer showing connected to update server.

**To Reproduce**
Auto-upgrade nebra outdoor hotspot.

**Expected behavior**
No change in wifi connectivity and hotsport to show and be connected to nebra dashboard and update servers.

**Comment by shawaj** [comment]
Relates to freshdesk ticket https://nebra.freshdesk.com/a/tickets/312983 and balena device https://dashboard.balena-cloud.com/devices/2f59264c716e16b95547c58749a14965/summary

**Comment by shawaj** [comment]
Relates to #83 #137 #132
