### ISSUE TITLE
Enable flake8

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-config#140]
**User Story**
As a developer I should have consistent linting standards across all repos to reduce friction while coding.

**Notes**
[Commented out](https://github.com/NebraLtd/hm-config/blob/24b1466d75ebf03865a1fbb07f47781c0a7e35ab/.github/workflows/linter.yml#L51). Most of the work will be fixing the linting after enabled.

**Acceptance Criteria**
- Flake8 runs as part of build

**Comment by vpetersson** [comment]
Good catch. Yeah we should definitely enforce this.
