### ISSUE TITLE
Improve RockPi GPIO support

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-config#157]
Blocked by: #96 

There are improvements to make after #96 lands:

- Reconsider [mraa_gpio#mraa_gpio_write](https://github.com/NebraLtd/hm-config/blob/76d0f669f7bd1d48e1721c58c10855a447f6f0f0/gatewayconfig/gpio/mraa_gpio.py#L3). Should this be added to `start-gateway-config.sh` instead? What is the root cause for needing to do this with the LED as well? Can it be addressed a different way?
- Currently [ignoring hadolint](https://github.com/NebraLtd/hm-config/blob/76d0f669f7bd1d48e1721c58c10855a447f6f0f0/Dockerfile#L72) recommendations for libmraa in Dockrefile:

```
/github/workspace/Dockerfile:72 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
```
- [PREVENT_START_GATEWAYCONFIG](https://github.com/NebraLtd/hm-config/blob/76d0f669f7bd1d48e1721c58c10855a447f6f0f0/start-gateway-config.sh#L23) improvements. Is this a pattern we want to add to all repos?
- Use [buster-stable](https://github.com/NebraLtd/hm-config/blob/76d0f669f7bd1d48e1721c58c10855a447f6f0f0/Dockerfile#L73) radxa repo once available: https://forum.radxa.com/t/issue-with-libmraa-unable-to-locate-package/7957/7
- Add [Radxa APT key](https://github.com/NebraLtd/hm-config/blob/76d0f669f7bd1d48e1721c58c10855a447f6f0f0/Dockerfile#L75) into repo instead of doing wget.
- Investigate [mraa pin factory](https://github.com/gpiozero/gpiozero/issues/563) for gpiozero. Scope this out a little and add a ticket for follow up work.

**Comment by shawaj** [comment]
FYI https://github.com/radxa/apt/issues/17#issuecomment-989815347

**Comment by shawaj** [comment]
Also FYI https://github.com/radxa/meta-radxa/pull/1
