### ISSUE TITLE
Wi-Fi Configuration Sometimes Failing.

### ISSUE THREAD

**Issue by ryanteck** [NebraLtd/hm-config#16]
This is starting to appear slightly more since we've started shipping. Original posts below. This post to now track those affected.

Phones Affected:
- Google Pixel 5 Running Android 11
- iPhone X
- iPhone SE Gen 2 running 13.7
- Google Pixel 4A running Android 11
- Oppo A54 5G

**Comment by vpetersson** [comment]
@ryanteck do we know what iPhone this happened on? Also, I'd need a second miner to test this as mine is mounted outdoors.

**Comment by ryanteck** [comment]
@vpetersson I believe this customer was an SE but it's on across a few models so suspect it's hardware independant.

I'm going to do some more testing and tweaking today to see if I can replicate it X out of X times.
