### ISSUE TITLE
Manual triggered Bluetooth GATT advertisement doesn't work on RAK devices

### ISSUE THREAD

**Issue by MuratUrsavas** [NebraLtd/hm-config#170]
Even though we've fixed the button issue on RAK devices (NebraLtd/hm-pyhelper#125), the Bluetooth GATT advertisement does not work as expected with Helium Mobile App. (We also needto check whether this is only related to RAK devices or not)

Bluetooth paring works if gateway-config container starts after a reboot or manual restart. But it does not work with button trigger.

Another problem is, the GATT advertisement starts after 10-15 seconds later after pulling the finger from the button. This doesn't look OK.

**Acceptance criteria**
- Advertisement started if button held down for 2 seconds
- Advertisement turned off after 5 minutes
- Add documentation to helium-miner-sofware with a checklist for supporting new hardware, include this as a step.

**Comment by MuratUrsavas** [comment]
Relevant code section:

https://github.com/NebraLtd/hm-config/blob/master/gatewayconfig/gatewayconfig_app.py#L98

**Comment by marvinmarnold** [comment]
@MuratUrsavas added some AC. Also, this fix might be as simple as defining [BALENA_DEVICE_TYPE](https://github.com/NebraLtd/hm-pyhelper/blob/e81fa52a1ff516690f205a0df75ed57021ff9135/hm_pyhelper/hardware_definitions.py#L15) in the RAK fleets. 

But this is also related to: https://github.com/NebraLtd/hm-pyhelper/issues/69. It would be nice if we could detect SBC without relying on an env var.

**Comment by MuratUrsavas** [comment]
> @MuratUrsavas added some AC.
:+1: Thanks @marvinmarnold.

By the way I've handed this issue over to @pritamghanghas per @vpetersson's request.

**Comment by pritamghanghas** [comment]
@marvinmarnold @MuratUrsavas I haven' been able to reproduce it. Works for me every time. Across reboots as well.

**Comment by MuratUrsavas** [comment]
This was probably me getting hit to #104 in multiple attempts. I was expecting a new connection in my every trial, but the device was missing it in another way. This also explains the erratic behavior of my tests.

**Comment by marvinmarnold** [comment]
This is working but may be getting confused with issues caused by: https://github.com/NebraLtd/hm-config/issues/104
