### ISSUE TITLE
Fast blinking light when no obvious issues on diagnostics (showing All Ok on diag page)

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-config#188]
We have an issue on both ROCK Pi and RasPi miners (indoor and outdoor) where the status LED does the fast blink - which supposedly shows an error (failing PF diagnostic) - but on the diagnostics page it shows "All Ok" and looks like Eth, BT, ECC and LoRa are all working fine.

So it seems like this status is getting stuck somehow.

Ref: https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1649362757425709

**Comment by MuratUrsavas** [comment]
Right now my device stops slow blinking after some time and the green LED stays on forever.

**Comment by shawaj** [comment]
That's the correct functionality @MuratUrsavas :-)

**Comment by shawaj** [comment]
@marvinmarnold does https://github.com/NebraLtd/hm-config/pull/189 fix this?
