### ISSUE TITLE
Maker App stuck while configuring Wi-Fi in the process of onboarding

### ISSUE THREAD

**Issue by posterzh** [NebraLtd/hm-config#195]
On this Rockpi miner, after entering the Wifi password, the maker-app stuck.

Rockpi miners:
- https://dashboard.balena-cloud.com/devices/1af94fdfe4271c791a84afcbe5e4d7e2/summary
- https://dashboard.balena-cloud.com/devices/150b93b8e1ab5af1e1e8959aba7e81b4/summary

This is tested after applying this PR(https://github.com/NebraLtd/hm-config/pull/193)

Screenshot:
![image](https://user-images.githubusercontent.com/91350131/166289891-a344711e-e18c-418a-8721-c79968a3a54b.png)

**Comment by posterzh** [comment]
This issue is not the problem of `hm-config` service in the hotspot nor `nmcli` command, but the unreliable call to the Helium API on the 'maker-app'. Possible solution may be to use the 3rd party Helium shadow API in the maker app.

**Comment by vpetersson** [comment]
@posterzh Don't see any good reason *not* to use the private API for the app.

**Comment by posterzh** [comment]
Ok

**Comment by posterzh** [comment]
@marvinmarnold Ok, I will keep an eye and close after it's in production.

**Comment by marvinmarnold** [comment]
@Andrewsopoku can you confirm that you set all the environment variables from the current sample for the latest release?

**Comment by marvinmarnold** [comment]
@posterzh I get an error that Helium API is down on both my Android and iOS. 

![signal-2022-05-16-141004_001](https://user-images.githubusercontent.com/1311030/168665262-4dde9afb-40bb-4197-a984-768fc73d2a34.jpeg)

Also, I took a closer look at the endpoint details and it looks like we should be cycling through our private api, api.helium.io, then api.helium.wtf.

![Screen Shot 2022-05-16 at 2 15 05 PM](https://user-images.githubusercontent.com/1311030/168665704-26c8f87e-e16a-4712-acd7-0e130f87b329.png)

In any case, all three API endpoints really do seem to be down now:

```
✗ curl https://api.helium.io/v1/hotspots/11XTwHUxPd6DEeq13p7JE4bewBM5Nm6kF6vxKCNANaDZcRxJxwv

{"error":"Not Found"}%

✗ curl https://api.helium.wtf/v1/hotspots/11XTwHUxPd6DEeq13p7JE4bewBM5Nm6kF6vxKCNANaDZcRxJxwv

<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
</body>
</html>
```

I'll test again later.


Balena:
https://dashboard.balena-cloud.com/devices/1af94fdfe4271c791a84afcbe5e4d7e2/summary

**Comment by posterzh** [comment]
@marvinmarnold Thanks for good catch. I am going to add https://api.helium.wtf to the cycling list when calling the Helium API.

**Comment by marvinmarnold** [comment]
Not a blocker for this as long as we are sending transactions to api.helium.io

**Comment by marvinmarnold** [comment]
@posterzh this has been fixed. But there is another issue that is blocking onboarding that needs to be prioritized ASAP: https://github.com/NebraLtd/maker-starter-app/issues/160

**Comment by posterzh** [comment]
@marvinmarnold I will take a look.
