### ISSUE TITLE
Diagnostic processor should call diag less frequently

### ISSUE THREAD

**Issue by pritamghanghas** [NebraLtd/hm-config#202]
currently hm-config calls diagnostic json end point every 60 seconds.  In hm-config LedProcessor is its only user.
Side effects of running diagnostics this freqenty:
1. Diagnostics logs are flooded with debug from perform_hw_diagnostics
2. I think this is making diag uploads also unreliable, there seems strange flipping of ship=false in some cases.
3. this keeps ecc busy unnecessarily and might interference with miner operations. (not verified yet if this is having an impact)

Acceptance Criteria:
- [ ] Diagnostics endpoint is only called on demand
- [ ] BT Diagnostics should continue to work and provide up to date diagnostics

**Comment by pritamghanghas** [comment]
[this one](https://github.com/NebraLtd/hm-diag/issues/372) might be related.

**Comment by KevinWassermann94** [comment]
This can be merged to production too

**Comment by pritamghanghas** [comment]
this is already merged.

**Comment by pritamghanghas** [comment]
checked again. hm-config hash carrying this is already in production closing.
