### ISSUE TITLE
iOS issue index out of range/ invalid wire type

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-config#26]
Latest iOS iPhone 12  v3.2.1 app

![image1](https://user-images.githubusercontent.com/3359418/119658758-6c00ef00-be25-11eb-9ecb-257055c7d994.png)
![image0-5](https://user-images.githubusercontent.com/3359418/119658772-6d321c00-be25-11eb-8b11-a5e2f5f86200.png)

**Comment by shawaj** [comment]
From customer...

no worries; the offset number has been different couple of time; I've got #206, #187, 196,  367, 361

**Comment by ryanteck** [comment]
This wasn't actually a software issue, turns out it was the compute module board had become disconnected.

**Comment by shawaj** [comment]
@luke#2560 on Discord just for future reference

**Comment by shawaj** [comment]
@ryanteck I'm wondering if we should get them to glue/tape the cm in place. Guess we see if this happens to more people

Or clip it somehow

**Comment by ryanteck** [comment]
Possibly could be that they could do with gluing it in. Or maybe a bit of tape. Not sure which is best.

**Comment by shawaj** [comment]
For future reference also...

No. looks fine now.
I did the following:
1. Put the RPi module where it is supposed to be when I received the Nebra
2. add custom Antenna (RAK5.8) to Nebra
3. PowerOn
4 Follow instructions on App --> Offset errors

5. Turn off device
6. Re-Seed RPi Chip (with the 2 small clips)
7. Add the Nebra Stock (3dbi) atenna
8. Turn On

9. Try to config using app again --> Success

![Screenshot_20210526-140528_Discord](https://user-images.githubusercontent.com/3359418/119664737-8ccc4300-be2b-11eb-87d6-8d769869f545.jpg)

**Comment by shawaj** [comment]
@ryanteck sounds like the daughterboard was loose and the CM - so maybe this won't happen when daughterboard is properly secured. Let's monitor the situation
