### ISSUE TITLE
Emoji in SSIDs can cause issues

### ISSUE THREAD

**Issue by ryanteck** [NebraLtd/hm-config#29]
Possibly see if it's possible to add some handling for Emojis in SSIDs as this seems to be causing some issues.

**Comment by shawaj** [comment]
Relates to https://github.com/helium/hotspot-app/issues/879

**Comment by marvinmarnold** [comment]
@vladimirpoleshko can you upload image/video of this working correctly so we can close it out?

**Comment by vladimirpoleshko** [comment]
Here is a preview. Issue not with an emoji. Relates to different issues.

https://user-images.githubusercontent.com/5319549/135462418-dfecc82d-bbf8-42a7-8178-7400cf0b4b1a.MP4
