### ISSUE TITLE
Wi-Fi Error in diagnostics. No MAC. 

### ISSUE THREAD

**Issue by pooley92** [NebraLtd/hm-config#32]
Tested in the following scenario. 
While plugged into ethernet and wi-fi not setup. 
Two of my hotspots v2 version exhibit an error with the Wi-Fi adapter. 
WLAN0 MAC | FF:FF:FF:FF:FF:FF

Top LED starts flashing fast.

Firmware is 2021.06.03.0

Shawaj says:
"I might be wrong but I think the WiFi Mac is a soft Mac and not fixed. So could be software." as I think it may also be software related. This is because if either hotspot is rebooted the MAC is found again and no error for a period of time. 

Issue is related to the hotspots in this ticket: 245083

**Comment by shawaj** [comment]
Related to https://github.com/NebraLtd/helium-miner-software/issues/72

**Comment by shawaj** [comment]
Related to https://github.com/NebraLtd/hm-diag/issues/142
