### ISSUE TITLE
No Onboarding key

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-config#45]
We've apparently had a lot of 'No Onboarding key' errors based on [this Slack thread](https://pisupply.slack.com/archives/C021GG30JP3/p1625059651187700).

There's even a [spreadsheet](https://docs.google.com/spreadsheets/d/1l4ZW852Y9CSEwKOCR9VSW8w9xkPkbx8XJOPWR9Hx2Ow/edit#gid=0) that tracks them.

I don't know what the root cause is at this point, but for whatever reason the "fix" is to just update the key. That's of course not an appropriate solution.

**Comment by shawaj** [comment]
So I believe the issue is that @ryanteck created a program that required a config file either from GitHub or our server to configure the ECC correctly / get the correct key from it. The download of this file was getting blocked by the China firewall and consequently meant it was uploading the wrong key to our server.

**Comment by vpetersson** [comment]
From @shawaj on Slack: 
> I'll dig out the command to fix it. It's basically just to go onto the miner container on balena, grab the public key of the ECC and update it in our onboarding server and push it to helium

**Comment by Tetytety** [comment]
Hello, I have the same "Onboarding error" miner reports no_onboarding-key or Onboarding error on nebra outdoor miner and I can't start pairing. How do I solve the problem so that I can run miner? Thanks

**Comment by vpetersson** [comment]
@Tetytety You need to reach out to support.

**Comment by Tetytety** [comment]
I did it. but no response yet, so I'm trying to find a solution everywhere on the internet. So far unsuccessfully. I hope to get a response from support soon. 
thank you for answer 😊

**Comment by vpetersson** [comment]
Long story short, we need to re-register the device with Helium. Hence this is unfortunately not you can fix on your end.

**Comment by Tetytety** [comment]
I understand, so I can only wait.You have some idea when a solution could be found? Thanks 😊

**Comment by TheDivineAges** [comment]
I was in the process of building a rak miner and was to the point of setting up hip19 and the power went out. Now I can't reconnect to it to finish the onboarding key set up. I tried, out of curiosity, to connect to helium obviously it told me no key. I was using putty, is Balenca easier or better? Also, I can't find this new onboarding info, that fixed some issue with hip19. Also, the link I was using from rak no longer works with the instructions. And last time I looked at helium the link wasn't working either. Is there somewhere else I can get the doc?

**Comment by shawaj** [comment]
@TheDivineAges you are trying to create your own DIY hotspot?

**Comment by TheDivineAges** [comment]
Yes. I’m actually trying to develop one. But the one in question is basically rak set. In makes an earlier rak model. I did it some time back and haven’t been able to get it fixed. I even bought a parley labs sd and put my original hotspot sd in cuz that’s what was suggested to me o. The discord. But the onboarding key seems to be a step I must do through the rak hat.

Sent from my phone🔺🔻

On Jul 20, 2021, at 8:47 PM, Aaron Shaw ***@***.***> wrote:

﻿

@TheDivineAges<https://github.com/TheDivineAges> you are trying to create your own DIY hotspot?

**Comment by shawaj** [comment]
@TheDivineAges you can't create your own hotspot without being an approved maker.

You can create a data only hotspot but you won't be able to earn any HNT from it.

**Comment by shawaj** [comment]
@vpetersson guess we can close this issue out now as think we have resolved it?

**Comment by vpetersson** [comment]
Yep. We have a separate tracker for it.
