### ISSUE TITLE
Onboarding Key - list index out of range

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/hm-config#63]
Since the latest update (19th August) on Testnet and 20th August on production the following error seems to occur:

20.08.21 10:34:41 (+0200)  gateway-config    File "config_program.py", line 64, in <module>
20.08.21 10:34:41 (+0200)  gateway-config      onboardingKey = str(public_keys_file[3])
20.08.21 10:34:41 (+0200)  gateway-config  IndexError: list index out of range
20.08.21 10:34:41 (+0200)  gateway-config  Sentry is attempting to send 1 pending error messages
20.08.21 10:34:41 (+0200)  gateway-config  Waiting up to 2 seconds
20.08.21 10:34:41 (+0200)  gateway-config  Press Ctrl-C to quit
20.08.21 10:34:42 (+0200) Service exited 'gateway-config sha256:5892e5e1fdd2f6644d586c982ec619b07ea70b50b7d323ab44cbd31afda6ec31'

This causes an error in the diagnostics 
20.08.21 10:37:00 (+0200)  diagnostics  ERROR:root:The public keys from the file were obtained with an unknown error

Causing the hotspot name to not show in the diagnostics page and the Helium address to be incorrect

**Comment by vpetersson** [comment]
Solved in #65.
