### ISSUE TITLE
Awaiting Location Assertion

### ISSUE THREAD

**Issue by ccavusoglu0** [NebraLtd/hm-config#67]
2 of my hotspots stuck at "Awaiting Location Assertion" status even though they were asserted. 
I tried to swap their location and reassert them while waiting support (ticket  #261699) , but that also didnt help. 
As I found on discord, people who has this problem also have "no onboarding key" issue. But I dont have such problem. They're able to create challenge and etc.. They just don't find witness yet I dont know if it is related. 

![237095531_311149404122471_7230653477802997800_n](https://user-images.githubusercontent.com/13016484/130365146-a690d185-fcc5-41a6-9a86-7476b2330d35.jpg)

**Comment by shawaj** [comment]
This just means that the miner hasn't loaded fully yet. Once the miner loads fully it should repopulate

**Comment by ccavusoglu0** [comment]
Does it really take 12 days to fully load? Because it was 12th day that I thought something is wrong and swapped their location to re-assert. 
Tangy Tin Alpaca

**Comment by ccavusoglu0** [comment]
It turns out that this issue is related with
 https://github.com/helium/miner/issues/1031

My friends contacted to Sensecap to set region manually for a temporary solution and it is fixed. It seems like bobcats somehow handle this situation in backend. 
I would also appreciate if a help like that temporarily. Ticket number #273131
