### ISSUE TITLE
AddGatewayCharacteristic failure but gateway is successfully added

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-config#68]
UI shows an error when adding a new gateway. Despite the error message, the gateway was successfully added. Additional logging has been added in #61 to better debug next time. 

![Screenshot_20210823-175637.png](https://images.zenhubusercontent.com/6111782bbed147dc514083ae/ce3d587d-5951-4e17-8f4c-7a4d460f6298)

Related to #28

**Comment by posterzh** [comment]
This error was fixed after fixing `Incorrect password leads to characteristic error`(https://github.com/NebraLtd/hm-config/issues/105) by https://github.com/NebraLtd/hm-config/pull/129.
