### ISSUE TITLE
Better error handling when miner keys are present but malformed

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-config#80]
Current behavior is to continue with key values set to `False`. This allows the program to continue but may result in unexpected behavior. Ideally, we should show an on screen error to the user.

Originated: https://github.com/NebraLtd/hm-config/pull/69#discussion_r695690794

**Comment by shawaj** [comment]
@vpetersson in that case it would be if it can't connect to the miner over RPC presumably?

**Comment by vpetersson** [comment]
We haven't implemented this yet.
