### ISSUE TITLE
End-to-end test Rock Pi 4 with HAT hm-config hm-diag

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-config#82]

**Comment by marvinmarnold** [comment]
SPI is working on RockPi images but is still not over the line with Balena. Follow up work includes:
- https://github.com/NebraLtd/product-management/issues/12
- https://github.com/NebraLtd/hm-config/issues/96
- https://github.com/NebraLtd/hm-miner/issues/31
