### ISSUE TITLE
Forgetting Wifi network does not work

### ISSUE THREAD

**Issue by Funkton** [NebraLtd/hm-config#83]
Forgetting the Wifi from the Helium app does not work. It continually has the ssid and connects to the router even after selecting to forget the network.

**Comment by shawaj** [comment]
Think this is a bug in the Helium app but if you hold your finger on it to forget in the app, but when it prompts you to enter your WiFi password again just click cancel and it will be forgotten

**Comment by shawaj** [comment]
Actually looks like they might have fixed that bug in https://github.com/helium/hotspot-app/pull/650

Also relates to https://github.com/helium/hotspot-app/issues/602

**Comment by shawaj** [comment]
@Funkton did you get this to work?

**Comment by Funkton** [comment]
I managed to delete the connection files that were causing the issue. There were multiple copies of the same which may have been confusing the system.

**Comment by shawaj** [comment]
Think this might be the root cause:
https://github.com/NebraLtd/hm-config/blob/cf305ef6211484213630408c6fcadddd2e02f35c/gatewayconfig/bluetooth/characteristics/wifi_remove_characteristic.py#L49-L55

**Comment by vpetersson** [comment]
@posterzh Let's look at this in next sprint.

**Comment by posterzh** [comment]
> @posterzh Let's look at this in next sprint.

Sure
