### ISSUE TITLE
Nebra Miner DHCP Issues with Wifi

### ISSUE THREAD

**Issue by derjohn** [NebraLtd/hm-config#84]
We observed, that the, miner has issues with DHCP and/or associating with the Wifi.

- It might be the case, that it happens only if multiple Wifi Hotspots broadcast the same SSID.  In our case it happenend with 1.) Fritz! Repeater 2.) Unifi multiple access points

- The miner will either "forget" it's IP after some hours OR will not get an IP on at setup time.

**Comment by shawaj** [comment]
@derjohn are you assigning a static IP based on the Mac address?

**Comment by derjohn** [comment]
Yes,
for the Fritz!Box 7590 case "Issue always the same IP with DHCP" and 44158/TCP port-forward. (I think most routers will need a DHCP MAC-IP mapping for the port-forward target).

I case of the Unifi setup I can't remember.

ATM we connected the Nebra via Ethernet to a router which is configured as Wifi Client.

rgds,
j.

**Comment by shawaj** [comment]
That could be the issue. We have a known bug where sometimes the WiFi Mac address gets overriden

**Comment by derjohn** [comment]
But according to the diag interface and/or the Fritzbox Web GUI the device didn't have an IP at all. If the bug just makes DHCP request with a different MAC, it should just get a different IP?
