### ISSUE TITLE
Deployment Issue ...

### ISSUE THREAD

**Issue by Engr-Talha** [NebraLtd/hm-config#85]
Hello! I am new to Baleno, I want to deploy the code on Raspberry pi 4 with a Baleno image,  then I run commands as given in the repository but unfortunately, it is not running when I run the commands for a locally running environment it gives me that error.

python3: can't open file 'minerconfig': [Errno 2] No such file or directory

As I don't know how to resolve this because this file does not exist and I think we are initiating using this command. 

Cross-compile locally and deploy to Balena: **balena deploy dev-XXX --build** (preferred method). 
Please tell me what to write in the place of  dev-XXX because when I run this command it gives me an error :
**Error:** : BalenaApplicationNotFound: Application not found: dev-XXX

I have tried all the methods that could be used to solve this problem. But I don't know where I am doing the mistakes. Please help to deploy this code on ubuntu locally and also on Baleno cloud.

**Comment by vpetersson** [comment]
This isn't supported. We don't support 3rd party miners at this point.
