### ISSUE TITLE
Rockpi: Add GPIO support

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-config#96]
gpiozero and RGPIO are currently being used to interact with GPIO but do not support RockPi. As part of validating RockPi viability, a [flag was added](https://github.com/NebraLtd/hm-config/blob/marvinmarnold/rockpi/gatewayconfig/gatewayconfig_app.py#L93) to disable GPIO completely on rockpi.

We have already validated that GPIO control will work on RockPi either with [libmraa](https://wiki.radxa.com/Rockpi4/dev/libmraa) or directly modifying the filesystem, eg:

```
   cd /sys/class/gpio
   echo 157 > export
   cd gpio157
   echo out > direction
   echo 1 > value     # output high
   echo 0 > value     # output low
```

But ideally, we want to use a solution that is gpiozero compatible so that the least amount of code needs to be rewritten. [gpiozero supports gpiod](https://www.ics.com/blog/gpio-programming-exploring-libgpiod-library) and that looks like the most promising way to get things working.

**Additional resources**
https://wiki.radxa.com/Rockpi4/hardware/gpio
https://github.com/gpiozero/gpiozero/issues/563
https://github.com/gpiozero/gpiozero/issues/840#issuecomment-593548271
https://github.com/underground-software/RPi.GPIO2
http://abyz.me.uk/lg/py_lgpio.html
https://gpiozero.readthedocs.io/en/stable/api_pins.html

**Comment by shawaj** [comment]
Any progress on this @marvinmarnold ?

**Comment by marvinmarnold** [comment]
Haven't touched this since then. Is the goal only to get a full solution. Or is it helpful for certification purposes or something to [cherry-pick](https://github.com/NebraLtd/hm-config/commit/1e13696f3025fd86f6839a3e8085dc54f30fbd2d#L27) some changes that let rockpi be used without GPIO?

We'll need to change the code in a few places to replace RGPIO for rockpi.

**Comment by shawaj** [comment]
@marvinmarnold we have two types of certification:

- compliance testing (CE / FCC etc)
- DeWi / Helium approval

For the latter it needs to be fully functional.

For the former we mainly need the radio elements (hm-pktfwd) working. But that requires GPIO support I believe?

Looks like diag is also failing with the lack of GPIO support currently too see https://github.com/NebraLtd/hm-diag/issues/237

**Comment by shawaj** [comment]
I guess the main question is whether we can support the two devices with a single set of docker images and docker-compose

Currently I'm not convinced that we can for diag and config and possibly miner

**Comment by marvinmarnold** [comment]
Accidentally closed.

**Comment by marvinmarnold** [comment]
@shawaj @vpetersson tl;dr: status LED is working on [native](https://wiki.radxa.com/Rockpi4/downloads) RockPi image but not Balena. Button is not working on either.

gpiozero is built for Raspberry Pi and uses "[pin factories](https://gpiozero.readthedocs.io/en/stable/api_pins.html#changing-the-pin-factory)" like RPi.GPIO that are all dependent on Raspberry Pi. It is possible to write a custom pin factory but that process is [not trivial](https://github.com/gpiozero/gpiozero/blob/master/gpiozero/pins/rpigpio.py). 

That means the path of least resistance is to replace gpiozero with a custom lower level implementation when running on RockPi. Libmraa is the [recommended](https://wiki.radxa.com/Rockpi4/dev/libmraa) tool on RockPi. But even after following the Radxa APT instructions, I'm unable to install libmraa on a Balena image. It results in `Unable to locate package libmraa`. On a native rockpi image, it installs fine.

On Balena, it is possible to [install libmraa from source](https://github.com/eclipse/mraa/blob/master/docs/building.md#basic-build-steps). But even after installing from source on Balena, manipulating the status LED directly has no effect. The following command works on native RockPi but not Balena: `sudo mraa-gpio set 18 1`. Also worth noting that there has been no movement from the gpiozero core team to [add support for libmraa](https://github.com/gpiozero/gpiozero/issues/563).

Next steps for LED:

- Contact Balena support about why APT can't be found and why manually built libmraa does not work.
- Look into extra steps to expose [/sys/class/gpio](https://wiki.radxa.com/Rockpi4/hardware/gpio#GPIO_number) on the container 

I need input for next steps for the button. `mraa-gpio monitor 16` never changes value on either native RockPi or Balena. Other than contacting RockPi support, I'm not sure how else to proceed.

**Comment by marvinmarnold** [comment]
Update: Toggling status LED is working on both native RockPi and Balena now. Unsure if a restart was needed or something else fixed it.

**Comment by shawaj** [comment]
> Look into extra steps to expose /sys/class/gpio on the container

It has the label `io.balena.features.sysfs: 1` set already so should be available

**Comment by shawaj** [comment]
This works to turn the green LED on... (pin 18 / GPIO4_D4)

```
   echo 156 > /sys/class/gpio/export
   echo out > /sys/class/gpio/gpio156/direction
   echo 1 > /sys/class/gpio/gpio156/value
```

**Comment by shawaj** [comment]
also @marvinmarnold was just looking at the start script...

https://github.com/NebraLtd/hm-config/blob/master/start-gateway-config.sh

This gives following errors:
```
 gateway-config  /opt/start-gateway-config.sh: 14: /opt/start-gateway-config.sh: cannot create /sys/kernel/debug/bluetooth/hci0/adv_channel_map: Directory nonexistent
 gateway-config  /opt/start-gateway-config.sh: 16: /opt/start-gateway-config.sh: cannot create /sys/kernel/debug/bluetooth/hci0/adv_min_interval: Directory nonexistent
 gateway-config  /opt/start-gateway-config.sh: 17: /opt/start-gateway-config.sh: cannot create /sys/kernel/debug/bluetooth/hci0/adv_max_interval: Directory nonexistent
```

Guess this will need adressing also

**Comment by shawaj** [comment]
actually, ignore my comment above - i think the device has a broken / temperamental bluetooth/wifi chip. I can't reproduce this on a different device. 

The only worrying thing is that this is a brand new device....I don't understand how/why the rf chip is not playing ball.

I wonder if the weirdness with wifi/ble is a driver issue in balena/linux

**Comment by shawaj** [comment]
FYI https://forum.radxa.com/t/issue-with-libmraa-unable-to-locate-package/7957

**Comment by vpetersson** [comment]
Also a relevant find:
https://github.com/balena-io-playground/hello-python-edison

It's for Edison but is using the libmraa library on Balena

**Comment by marvinmarnold** [comment]
> FYI https://forum.radxa.com/t/issue-with-libmraa-unable-to-locate-package/7957

I've added some notes here. My current understanding of the issue is that we are running 32bit `raspberry-pi-debian-python` images on 64 bit hardware. Radxa has not published a 32-bit variant of libmraa. I tried changing the apt source line to `deb [arch=arm64] http://apt.radxa.com/buster-stable/ buster main` but you get a lot of issues when trying to install:

```
# apt install libmraa:arm64
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libmraa:arm64 : Depends: libc6:arm64 but it is not going to be installed
                 Depends: libjson-c3:arm64 but it is not installable
                 Depends: libgcc1:arm64 but it is not installable
                 Depends: libstdc++6:arm64 but it is not installable
                 Depends: python2.7:arm64 but it is not installable
                 Depends: libpython2.7:arm64 but it is not installable
                 Depends: python3.7:arm64 but it is not installable
                 Depends: libpython3.7:arm64 but it is not installable
```

> Also a relevant find: https://github.com/balena-io-playground/hello-python-edison

The highlights here are:

- `resin/intel-edison-python:latest` comes with libmraa preinstalled: this is good to know but doesn't help out our images.
-  The [code](https://github.com/balena-io-playground/hello-python-edison/blob/f2c6613e97cbb428800282ca0fecef654b503bbf/app/hello.py#L11) has an example of toggling GPIOs. But not checking button presses which is the current issue.

I'm going to dig deeper now to figure out why `mraa-gpio monitor 16` isn't working for detecting button presses.

**Comment by shawaj** [comment]
@marvinmarnold are you doing:

```
mraa-gpio set 16 1
mraa-gpio monitor 16
```

As need to pull it high first

**Comment by shawaj** [comment]
Here is a button sample too
https://gist.github.com/navin-bhaskar/fbf4772bba7e95a651b0

**Comment by marvinmarnold** [comment]
> As need to pull it high first

@shawaj, exactly this was one of the missing pieces 

> mraa-gpio monitor 16

I still cannot get this to work. Even when pulling high first, this seems to reset the pin to `0`. 

Fortunately, reading directly from `/sys/class/gpio/gpio154/value` or using Python's `mraa.Gpio#read` both work fine. I'm unblocked now and can start implementing this in code.

**Comment by shawaj** [comment]
@marvinmarnold great stuff. That's good news.

Can we build an armhf / armv6 version ourselves of libmraa and just pull that in in the interim if RockPi are slow to fix?

**Comment by marvinmarnold** [comment]
Working on building now. Its really easy to follow [these](https://github.com/eclipse/mraa/blob/master/docs/building.md#build-dependencies) steps from a running container but the same is mysteriously [failing](https://github.com/NebraLtd/hm-config/runs/4360058578?check_suite_focus=true) when executed within Dockerfile. It fails both if added to runner or builder phase. I'm working around this for now but will eventually have to resolve.

Also @shawaj FYI the LEDs on the most recent ROCK Pi I received are inverted. Green facing board instead of yellow.

![signal-2021-11-29-171147](https://user-images.githubusercontent.com/1311030/143957379-f6ba4511-c6ff-4aab-abbe-8e335d858152.jpeg)

(old left, new right)

**Comment by shawaj** [comment]
Interesting re the LEDs. I'll clarify with Sunsoar.

I guess we should use the same as the old one on the left as that matches the LEDs on current indoor

What do you think?

**Comment by shawaj** [comment]
@marvinmarnold RockPi are going to build for armhf https://github.com/radxa/apt/issues/17#issuecomment-982202421

**Comment by vpetersson** [comment]
@marvinmarnold regarding the [build error](https://github.com/NebraLtd/hm-config/runs/4360058578?check_suite_focus=true), I'd break the build commands apart for better clarity of errors (also it doesn't matter since it's presumably in the build stage, so we throw it all away anyways). I'd also add a `cat` of `/opt/mraa/build/CMakeFiles/CMakeOutput.log` to see if that includes anything interesting.

**Comment by kashifpk** [comment]
Some boards have internal pull-up and pull-down resistors (including Raspberry Pi) while others don't. This might be a cause of not getting button presses on rockpi. There is a somewhat old discussion here: https://forum.radxa.com/t/gpio-voltage-short-circuit-to-gnd/1493/18 about some rockpi pins having pull up/down resistors and others not having those.

Not sure if this has been addressed before, just putting it out there. If there are no internal resistors then for proper button press reading we would need to pull the pin up or down using external resistor. In my experience if the board does not have built-in pull up/down resistors then reading inputs works randomly (that is the whole purpose of the resistors).

May be this can be determined by the technical manual of the rockpi board we're using?

**Comment by vpetersson** [comment]
@kashifpk this is not my forte, but does it matter which state it is in? All we care about is the delta (i.e. a button push). Since the button mechanically will revert to one state, it might not matter.

**Comment by kashifpk** [comment]
@vpetersson - Yes I had encountered this issue before with Arduinos I think. The issue is that before the button press (input) the pin needs to be in a known state. That's why we pull it up or down. Without it it's state is random, at times it might have some voltage on it and at other times it might not. So if our button works by grounding the pin it mean it pulls the pin state to down. But if the pin is already down (because we have not pulled it up) then a button press does not change the voltage reading on the pin. That is why some people even use external resistors with the raspberry pi too. And we have to specify that in the code with something like:

```python
# Set pin 10 to be an input pin and set initial value to be pulled low (off)
GPIO.setup(10, GPIO.IN, pull_up_down=GPIO.PUD_DOWN) # Set pin 10 to be an input pin and set initial value to be pulled low (off)
```

So even if rockpi supports internal pull resistors the library we use must provide a way to specify the pin's idle voltage state.

**Comment by shawaj** [comment]
@kashifpk yep see my comment above...
https://github.com/NebraLtd/hm-config/issues/96#issuecomment-981969183

**Comment by marvinmarnold** [comment]
Closed by: https://github.com/NebraLtd/helium-miner-software/pull/304
